# Generated by Django 4.1.5 on 2023-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
    ]
